org.gradle.jvmargs=-Xmx3G

minecraft_version=1.21.11
loader_version=0.18.4
java_version=21
minecraft_constraint=~1.21.11
parchment_mappings=2025.12.20

fabric_version=0.141.3+1.21.11
configurate_version=4.1.2
permissions_api_version=0.6.1
placeholderapi_version=2.8.2+1.21.10
sgui_version=1.12.0+1.21.11
commoneconomy_version=2.0.0
trinkets_version=3.10.0

