name: Publish to GitHub Packages

on:
  push:
    branches: [ master ]
  workflow_dispatch: {}

env:
  MINECRAFT_VERSION: 1.21.1
  JAVA_VERSION: 21
  VERSION: 1.9.2+1.21.1
  RELEASE_NAME: Solstice 1.9.2 for Minecraft 1.21.1
  MAVEN_USERNAME: ${{ github.actor }}
  MAVEN_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 21

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build (all versions)
        run: ./gradlew clean build

      - name: Publish to GitHub Packages
        env:
          MAVEN_USERNAME: ${{ env.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ env.MAVEN_PASSWORD }}
        run: ./gradlew publish
